{
  try {
    resolveMandatoryEndpoint("disruptor:foo?size=0",DisruptorEndpoint.class);
    fail("Should have thrown exception");
  }
 catch (  ResolveEndpointFailedException e) {
    assertEquals("Failed to resolve endpoint: disruptor://foo?size=0 due to: size found to be 0, must be greater than 0",e.getMessage());
  }
}
