{
  try {
    context.resolvePropertyPlaceholders("{{to}}");
    fail("No exception is thrown!");
  }
 catch (  Exception cause) {
    assertThat("Exception thrown is incorrect",cause,is(instanceOf(IllegalArgumentException.class)));
    assertThat("Exception message is incorrect",cause.getMessage(),is(equalTo("Property with key [to] not found in properties from text: {{to}}")));
  }
}
