{
  try {
    super.setUp();
    fail("Should have thrown an exception");
  }
 catch (  Exception e) {
    ResolveEndpointFailedException cause=assertIsInstanceOf(ResolveEndpointFailedException.class,e.getCause().getCause());
    assertTrue(cause.getMessage().endsWith("Unknown parameters=[{foo=bar}]"));
  }
}
