{
  if (finallyProcessor != null) {
    Throwable lastException=exchange.getException();
    exchange.setException(null);
    try {
      finallyProcessor.process(exchange);
      if (exchange.getException() == null) {
        exchange.setException(lastException);
      }
    }
 catch (    Exception e2) {
      LOG.warn("Caught exception in finally block while handling other exception: " + e2,e2);
      exchange.setException(e2);
    }
  }
}
