{
  Exception cause=exchange.getException();
  if (cause != null) {
    getExceptionHandler().handleException("Error during processing exchange. Will attempt to process the message on next poll.",exchange,cause);
  }
}
